apiVersion: v1
kind: Secret
metadata:
    name: common-bb
stringData:
    values.yaml: ENC[AES256_GCM,data:cKP+HwhVi6cBjXOhKusMDxopuHgTdA1ZvUNMTLy7JpfAKLKPkgt9h7SrPe9lz2ZgZU3c1CqtIgN76wE0sbFZPjNeO+YlTNhnwXdd6PS4T5BTMYKHvO9ieCY6gMkshXu1MuqEaZzWZfEGR5urqA71OCiUGq0=,iv:062IodkgY2QRZWRpCNIlBsJ3V3yhVN7L4fHgg+EIXeM=,tag:XM2b/0uNhWa1ZDh1ytPApg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2022-01-16T20:18:46Z"
    mac: ENC[AES256_GCM,data:SL218XMTDr7eEth9GsMIcwbfF9rcsXOo/iLGXj+R8nkZvy80UDbbtnRRHwlS7NApvor4E6r2FhvX2FX5HkW/xsEJNVPKMwha+pLbwjNhImlw92+ghm+v2M6AVev/fo7sJSLRamPU8WSM36mVmIbamogQzNb9jp4qhqX0hisVpVM=,iv:h90jLrIqafegOo81kN8+fD9UUGEbGPycGR/OtDMrMDY=,tag:TK8mNMh30FHPU6EOT31tYA==,type:str]
    pgp:
        - created_at: "2022-01-16T20:18:45Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMAyFvf09ijcMvAQ/9F+wsC/37dxxInBOrhGPY60BieOOSaVk+MF5BRy17C14K
            ac0p7miLRMTCaS3IVubg8+U95tw2gFpH3wsHZdXxe8tQrih7vq/d+r/KyWubnVNa
            g1wnz434aoRG7sxXZIR/1c/hDkDpOglaSO69DxY9nhEJIda5+6iR55hNdcxApJYb
            J8nUX9GKaqrVVqlC0rM0ZYGgFJKoI2ZAic7buYRnDFOgcDwPUwiNWXEWmHzo38g6
            uyXYdG1CnCQsPeSxyMv2WDD7OE6Ou36YgISpcvkyBGS7jkd/cogcSbdOY1QnVIfy
            IqDNwsqgbBlNvqWDMEWFfgKXHCcVe1P9JN/Etu3MR4Wq9Gwu6bW8xONXGwJnoJyY
            63RadOcgsProdk+1EoK30vQ5mBxhyTbBy7jlBKA8nyefb7ScExhxCx7E1/QHvEdy
            zIvG1EuCV1bQKcGYgje4bK+RVXJRJZ9WzhhM3LU3jbQjWl2jofeiAQK7wBkrqRlV
            PYiv1Vuj6hB66tZ4iNNjghTB7xxMzetLpzed7/4GaZFFhiHtHLe7rOnZkcLRc3dC
            71kFzmLnwM5ZSQBJ0IJMoigGq7ZhUAVqnFfLOkkmd75zEC1o2AG2TVcO7zk+Nqbo
            bNAVZOfuVmYSN1BBQJoZMWAQYXDpzybWGLlxWern+ctidXeVjRW98Ae1GYUGyNPS
            XgEAE4slWepjHMKwX4wCVJVOjXcGr61K7zXw0hvReJR0bs63fhpqhZ00rOGA5gdo
            gzZ+KTbFScpuJN9ioH80ZE9Y7v/4auT17q9lrWCrRLe/mD1ANWJOEyzWGvyzLJI=
            =OQxz
            -----END PGP MESSAGE-----
          fp: 893169918A62707F8A655474428F62C5014A9226
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
